DROP TABLE IF EXISTS Matricula;
DROP TABLE IF EXISTS User;

CREATE TABLE User (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS Course;

CREATE TABLE Course (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE Matricula (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_username VARCHAR(20) NOT NULL,
    course_code VARCHAR(10) NOT NULL,
    data_matricula DATE NOT NULL,
    FOREIGN KEY (user_username) REFERENCES User(username),
    FOREIGN KEY (course_code) REFERENCES Course(code)
);